export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST";
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS";
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL";

export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL";

export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT";

export const EMPLOYEE_LIST_REQUEST = "EMPLOYEE_LIST_REQUEST";
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS";
export const EMPLOYEE_LIST_FAILS = "EMPLOYEE_LIST_FAILS";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILS = "USER_LIST_FAILS";

export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAILS = "EMPLOYEE_DETAILS_FAILS";

export const EMPLOYEE_TASK_DETAILS_REQUEST = "EMPLOYEE_TASK_DETAILS_REQUEST";
export const EMPLOYEE_TASK_DETAILS_SUCCESS = "EMPLOYEE_TASK_DETAILS_SUCCESS";
export const EMPLOYEE_TASK_DETAILS_FAILS = "EMPLOYEE_TASK_DETAILS_FAILS";

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";

export const EMPLOYEE_TASK_DETAILSBYID_REQUEST =
  "EMPLOYEE_TASK_DETAILSBYID_REQUEST";
export const EMPLOYEE_TASK_DETAILSBYID_SUCCESS =
  "EMPLOYEE_TASK_DETAILSBYID_SUCCESS";
export const EMPLOYEE_TASK_DETAILSBYID_FAILS =
  "EMPLOYEE_TASK_DETAILSBYID_FAILS";

export const SOMEDETAILS_REQUEST = "SOMEDETAILS_REQUEST";
export const SOMEDETAILS_SUCCESS = "SOMEDETAILS_SUCCESS";
export const SOMEDETAILS_FAILS = "SOMEDETAILS_FAILS";
