export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILS = "NOTIFICATION_FAILS";

export const SEE_NOTIFICATION_REQUEST = "SEE_NOTIFICATION_REQUEST";
export const SEE_NOTIFICATION_SUCCESS = "SEE_NOTIFICATION_SUCCESS";
export const SEE_NOTIFICATION_FAILS = "SEE_NOTIFICATION_FAILS";
