export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAILS = "PROJECT_LIST_FAILS";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAILS = "PROJECT_DETAILS_FAILS";

export const PROJECT_CREATED_REQUEST = "PROJECT_CREATED_REQUEST";
export const PROJECT_CREATED_SUCCESS = "PROJECT_CREATED_SUCCESS";
export const PROJECT_CREATED_FAILS = "PROJECT_CREATED_FAILS";

export const TASK_CREATED_REQUEST = "TASK_CREATED_REQUEST";
export const TASK_CREATED_SUCCESS = "TASK_CREATED_SUCCESS";
export const TASK_CREATED_FAILS = "TASK_CREATED_FAILS";
