export const REPORT_CREATED_REQUEST = "REPORT_CREATED_REQUEST";
export const REPORT_CREATED_SUCCESS = "REPORT_CREATED_SUCCESS";
export const REPORT_CREATED_FAILS = "REPORT_CREATED_FAILS";

export const REPORT_VIEW_REQUEST = "REPORT_VIEW_REQUEST";
export const REPORT_VIEW_SUCCESS = "REPORT_VIEW_SUCCESS";
export const REPORT_VIEW_FAILS = "REPORT_VIEW_FAILS";

export const REPORT_SINGLEVIEW_REQUEST = "REPORT_SINGLEVIEW_REQUEST";
export const REPORT_SINGLEVIEW_SUCCESS = "REPORT_SINGLEVIEW_SUCCESS";
export const REPORT_SINGLEVIEW_FAILS = "REPORT_SINGLEVIEW_FAILS";

export const REPORT_UPDATE_REQUEST = "REPORT_UPDATE_REQUEST";
export const REPORT_UPDATE_SUCCESS = "REPORT_UPDATE_SUCCESS";
export const REPORT_UPDATE_FAILS = "REPORT_UPDATE_FAILS";

export const REPORT_REMARK_REQUEST = "REPORT_REMARK_REQUEST";
export const REPORT_REMARK_SUCCESS = "REPORT_REMARK_SUCCESS";
export const REPORT_REMARK_FAILS = "REPORT_REMARK_FAILS";

export const REPORT_VIEWBYUSER_REQUEST = "REPORT_VIEWBYUSER_REQUEST";
export const REPORT_VIEWBYUSER_SUCCESS = "REPORT_VIEWBYUSER_SUCCESS";
export const REPORT_VIEWBYUSER_FAILS = "REPORT_VIEWBYUSER_FAILS";
