export const REPORT_CREATED_REQUEST = "REPORT_CREATED_REQUEST";
export const REPORT_CREATED_SUCCESS = "REPORT_CREATED_SUCCESS";
export const REPORT_CREATED_FAILS = "REPORT_CREATED_FAILS";

export const REPORT_VIEW_REQUEST = "REPORT_VIEW_REQUEST";
export const REPORT_VIEW_SUCCESS = "REPORT_VIEW_SUCCESS";
export const REPORT_VIEW_FAILS = "REPORT_VIEW_FAILS";
